fragment GnirsImagingDetails on GnirsImaging {
    camera
    defaultWellDepth
    explicitReadMode
    explicitWellDepth
    filters {
      exposureTimeMode {
        signalToNoise {
          at {
            nanometers
          }
          value
        }
        timeAndCount {
          at {
            nanometers
          }
          count
          time {
            seconds
          }
        }
      }
      filter
    }
    initialFilters {
      exposureTimeMode {
        signalToNoise {
          at {
            nanometers
          }
          value
        }
        timeAndCount {
          at {
            nanometers
          }
          count
          time {
            seconds
          }
        }
      }
      filter
    }
    wellDepth
}

fragment GnirsSpectroscopyDetails on GnirsSpectroscopy {
    acquisition {
      explicitAcquisitionType
      explicitFilter
      exposureTimeMode {
        signalToNoise {
          at {
            nanometers
          }
          value
        }
        timeAndCount {
          at {
            nanometers
          }
          count
          time {
            seconds
          }
        }
      }
      skyOffset {
        p {
          arcseconds
        }
        q {
          arcseconds
        }
      }
    }
    camera
    centralWavelengths {
      centralWavelength {
        nanometers
      }
    }
    decker
    defaultDecker
    defaultWellDepth
    explicitDecker
    explicitFocusMotorSteps
    explicitGrating
    explicitPrism
    explicitReadMode
    explicitWellDepth
    filter
    grating
    ifu {
      fpu
      initialFpu
      telescopeConfigs {
        guiding
        offset {
          p {
            arcseconds
          }
          q {
            arcseconds
          }
        }
      }
    }
    initialCamera
    initialFilter
    initialGrating
    initialPrism
    prism
    telluricType {
      starTypes
      tag
    }
    wellDepth
    slit {
      fpu
      initialFpu
      defaultTelescopeConfigs {
        alongSlit {
          guiding
          q {
            arcseconds
          }
        }
        offsetMode
        toSky {
          guiding
          offset {
            p {
              arcseconds
            }
            q {
              arcseconds
            }
          }
        }
      }
      explicitTelescopeConfigs {
        alongSlit {
          guiding
          q {
            arcseconds
          }
        }
        offsetMode
        toSky {
          guiding
          offset {
            p {
              arcseconds
            }
            q {
              arcseconds
            }
          }
        }
      }
      telescopeConfigs {
        alongSlit {
          guiding
          q {
            arcseconds
          }
        }
        offsetMode
        toSky {
          guiding
          offset {
            p {
              arcseconds
            }
            q {
              arcseconds
            }
          }
        }
      }
    }
}


fragment GnirsDetails on ObservingMode {
  gnirsSpectroscopy {
    ...GnirsSpectroscopyDetails
  }
  gnirsImaging {
    ...GnirsImagingDetails
  }
}