fragment ScienceRequirementsDetails on ScienceRequirements {
  mode
}

fragment ConstraintSetDetails on ConstraintSet {
  imageQuality
  cloudExtinction
  skyBackground
  waterVapor
  elevationRange {
    airMass {
      min
      max
    }
    hourAngle {
      minHours
      maxHours
    }
  }
}

fragment TimingWindowDetails on TimingWindow {
  inclusion
  startUtc
  end {
    __typename
    ... on TimingWindowEndAt {
      atUtc
    }
    ... on TimingWindowEndAfter {
      after {
        seconds
      }
      repeat {
        period {
          seconds
        }
        times
      }
    }
  }
}

# NOTE: do not factor exposureTimeMode selections into a shared
# `ExposureTimeModeDetails` fragment. Grackle (the ODB server) raises a false
# "Fragment cycle" validation error when two sibling fragments spread the same
# fragment by name (see GPC-151); the selections below must stay inlined.

fragment GmosNorthLongSlitDetails on GmosNorthLongSlit {
  grating
  filter
  fpu
  centralWavelength {
    nanometers
  }
  xBin
  yBin
}

fragment GmosSouthLongSlitDetails on GmosSouthLongSlit {
  grating
  filter
  fpu
  centralWavelength {
    nanometers
  }
  xBin
  yBin
}

fragment GmosNorthImagingDetails on GmosNorthImaging {
  filters {
    filter
  }
  bin
}

fragment GmosSouthImagingDetails on GmosSouthImaging {
  filters {
    filter
  }
  bin
}

fragment Flamingos2LongSlitDetails on Flamingos2LongSlit {
  decker
  defaultDecker
  disperser
  filter
  fpu
  telluricType {
    tag
    starTypes
  }
  exposureTimeMode {
    signalToNoise {
      value
      at {
        nanometers
      }
    }
    timeAndCount {
      time {
        seconds
      }
      count
      at {
        nanometers
      }
    }
  }
  explicitReadMode
  explicitReads
  explicitDecker
  readoutMode
  defaultReadoutMode
  acquisition {
    exposureTimeMode {
      signalToNoise {
        value
        at {
          nanometers
        }
      }
      timeAndCount {
        time {
          seconds
        }
        count
        at {
          nanometers
        }
      }
    }
  }
  initialDisperser
  initialFilter
  initialFpu
}

fragment ghostDetectorConfigDetails on GhostDetectorConfig {
  binning
  defaultBinning
  defaultReadMode
  explicitBinning
  explicitReadMode
  readMode
  exposureTimeMode {
    signalToNoise {
      value
      at {
        nanometers
      }
    }
    timeAndCount {
      at {
        nanometers
      }
      time {
        seconds
      }
      count
    }
  }
}


fragment ghostIfuDetails on GhostIfu {
    defaultIfu1Agitator
    defaultIfu2Agitator
    explicitIfu1Agitator
    explicitIfu2Agitator
    ifu1Agitator
    ifu2Agitator
    resolutionMode
    stepCount
    blue {
        ...ghostDetectorConfigDetails
    }
    red {
        ...ghostDetectorConfigDetails
    }
    skyPosition {
      dec {
        degrees
      }
      ra {
        degrees
      }
    }
    slitViewingCameraExposureTime {
        seconds
    }
}


fragment VisitorDetails on Visitor {
    mode
    name
    centralWavelength {
      nanometers
    }
    totalRequestTime {
      seconds
    }
    agsDiameter{
      dms
      hms
    }

}

fragment Igrins2LongSlitDetails on Igrins2LongSlit {
  exposureTimeMode {
    signalToNoise {
      value
      at {
        nanometers
      }
    }
    timeAndCount {
      time {
        seconds
      }
      count
      at {
        nanometers
      }
    }
  }
  telluricType {
    tag
    starTypes
  }
}

fragment Flamingos2ImagingDetails on Flamingos2Imaging {
  filters {
    filter
    exposureTimeMode {
      signalToNoise {
        at {
          nanometers
        }
        value
      }
      timeAndCount {
        time {
          seconds
        }
        count
      }
    }
  }
  initialFilters {
    filter
    exposureTimeMode {
      signalToNoise {
        at {
          nanometers
        }
        value
      }
      timeAndCount {
        at {
          nanometers
        }
        count
        time {
          seconds
        }
      }
    }
  }
  defaultReadMode
  explicitReadMode
  defaultReads
  explicitReads
  defaultDecker
  explicitDecker
  readoutMode
  defaultReadoutMode
  explicitReadoutMode
}

fragment ObservingModeDetails on ObservingMode {
  instrument
  mode
  gmosNorthLongSlit {
    ...GmosNorthLongSlitDetails
  }
  gmosSouthLongSlit {
    ...GmosSouthLongSlitDetails
  }
  gmosNorthImaging {
    ...GmosNorthImagingDetails
  }
  gmosSouthImaging {
    ...GmosSouthImagingDetails
  }
  flamingos2LongSlit {
    ...Flamingos2LongSlitDetails
  }
  flamingos2Imaging {
    ...Flamingos2ImagingDetails
  }

  igrins2LongSlit {
    ...Igrins2LongSlitDetails
  }
  visitor {
    ...VisitorDetails
  }
  ghostIfu {
    ...ghostIfuDetails
  }

}


