"""
Build the client from the committed environment schemas.

The build merges the development and production schemas into
``graphql/schemas/merged.graphql``, runs ariadne-codegen once on it, and writes
a trimmed copy of every operation per environment and the schemas the client
checks before sending into the generated package. It also writes ``llms.txt``
with links to the hosted docs and availability notes for AI agents.
"""

import ast
import contextlib
import copy
import io
import re
import shutil
import tomllib
from dataclasses import dataclass
from pathlib import Path

import typer
from ariadne_codegen.exceptions import CodeGenException
from ariadne_codegen.main import client as run_ariadne_codegen
from ariadne_codegen.schema import load_graphql_files_from_path
from rich.markup import escape

from custom_plugins.capture_operations import CAPTURE_KEY
from custom_plugins.environment_defaults import DEFAULTS_KEY, DefaultsReport
from custom_plugins.environments import USER_ENVIRONMENTS
from gpp_client.cli import output
from gpp_client.trimmed_operations import lookup_trimmed_operation, operation_digest
from graphql import (
    FieldNode,
    GraphQLError,
    OperationDefinitionNode,
    TypeInfo,
    TypeInfoVisitor,
    Visitor,
    build_ast_schema,
    parse,
    print_ast,
    visit,
)
from scripts.availability import AvailabilityTables, availability_tables
from scripts.llms_txt import AvailabilityNotes, render_llms_txt
from scripts.schema_merge import (
    MergedSchema,
    SchemaMergeError,
    TypeConflict,
    merge_schemas,
)
from scripts.trim_operations import (
    EnvironmentOperations,
    generated_operations,
    trim_operations,
)

__all__ = [
    "BuildError",
    "BuildPaths",
    "BuildResult",
    "TypeConflict",
    "build",
    "schema_file",
]

MERGED_SCHEMA_HEADER = (
    "# Generated by scripts/build_client.py from the development and production\n"
    "# schemas. Do not edit.\n\n"
)

app = typer.Typer(add_completion=False)


def schema_file(schemas_dir: Path, environment: str) -> Path:
    """
    Return one environment's schema file in a schemas directory.

    Parameters
    ----------
    schemas_dir : Path
        Directory holding one schema per environment.
    environment : str
        Environment name, such as ``"production"``.

    Returns
    -------
    Path
        The environment's schema file.
    """
    return schemas_dir / f"{environment}.graphql"


class BuildError(RuntimeError):
    """
    Raised when the build cannot complete.
    """


@dataclass(frozen=True)
class BuildPaths:
    """
    Files the build reads and writes.

    Parameters
    ----------
    schemas_dir : Path
        Directory holding ``<environment>.graphql`` per environment; the
        merged schema is written next to them.
    operations_dir : Path
        Directory holding the ``.graphql`` operations, searched recursively.
    package_dir : Path
        The generated package, replaced on every build.
    codegen_config : Path
        The ariadne-codegen TOML config; the build fills in the paths.
    llms_txt : Path | None, optional
        Where to write ``llms.txt``, the usage notes for AI agents; not
        written when ``None``.
    """

    schemas_dir: Path
    operations_dir: Path
    package_dir: Path
    codegen_config: Path
    llms_txt: Path | None = None

    @classmethod
    def for_repo(cls, root: Path) -> "BuildPaths":
        """
        Return the paths used in a gpp-client checkout.

        Parameters
        ----------
        root : Path
            Repository root.

        Returns
        -------
        BuildPaths
            Paths under ``root``.
        """
        return cls(
            schemas_dir=root / "graphql" / "schemas",
            operations_dir=root / "graphql" / "operations",
            package_dir=root / "src" / "gpp_client" / "generated",
            codegen_config=root / "graphql" / "codegen.toml",
            llms_txt=root / "llms.txt",
        )

    def schema_path(self, environment: str) -> Path:
        """
        Return one environment's schema file.

        Parameters
        ----------
        environment : str
            Environment name, such as ``"production"``.

        Returns
        -------
        Path
            The environment's schema file.
        """
        return schema_file(self.schemas_dir, environment)

    @property
    def merged_schema_path(self) -> Path:
        """
        Return the merged schema file.

        Returns
        -------
        Path
            The merged schema file.
        """
        return self.schemas_dir / "merged.graphql"


@dataclass(frozen=True)
class BuildResult:
    """
    What a build produced.

    Parameters
    ----------
    merged_schema_path : Path
        The merged schema file written.
    conflicts : tuple[TypeConflict, ...]
        Elements left out of the merged schema because their type differs
        between environments.
    trim_summary : str
        What each environment does not receive, as Markdown for a PR body.
    """

    merged_schema_path: Path
    conflicts: tuple[TypeConflict, ...]
    trim_summary: str


def build(paths: BuildPaths) -> BuildResult:
    """
    Run the build pipeline.

    Parameters
    ----------
    paths : BuildPaths
        Files to read and write.

    Returns
    -------
    BuildResult
        What the build produced.

    Raises
    ------
    BuildError
        Raised when a schema file is missing, the schemas cannot be merged, an
        operation selects a field whose type differs between environments or
        that no environment has, codegen fails, an environment-specific field
        did not get a ``None`` default, a trimmed operation is invalid on its
        environment, or the trimmed lookup misses a query the generated client
        sends.
    """
    merged = _merge(paths)
    paths.merged_schema_path.write_text(
        MERGED_SCHEMA_HEADER + merged.sdl, encoding="utf-8"
    )
    _check_conflicting_selections(paths, merged)
    operation_strs, defaults = _run_codegen(paths)
    _check_environment_defaults(paths.package_dir, defaults)
    schemas = {env: _environment_schema(paths, env) for env in USER_ENVIRONMENTS}
    trimmed = [
        trim_operations(env, schemas[env], operation_strs) for env in USER_ENVIRONMENTS
    ]
    errors = [error for environment in trimmed for error in environment.errors]
    if errors:
        raise BuildError(
            "Trimmed operations are invalid:\n" + "\n".join(f"  {e}" for e in errors)
        )
    generated = generated_operations(operation_strs)
    _check_lookup_finds_sent_operations(paths, generated, trimmed)
    _write_trimmed(paths.package_dir, generated, trimmed)
    methods = _method_environments(paths.package_dir, trimmed)
    _write_environment_clients(paths.package_dir, methods)
    tables = availability_tables(merged.document, schemas, operation_strs)
    _write_bundled_schemas(paths)
    if paths.llms_txt is not None:
        paths.llms_txt.write_text(
            render_llms_txt(_availability_notes(methods, tables, trimmed)),
            encoding="utf-8",
        )
    return BuildResult(
        merged_schema_path=paths.merged_schema_path,
        conflicts=merged.conflicts,
        trim_summary=_trim_summary(trimmed),
    )


def _merge(paths: BuildPaths) -> MergedSchema:
    missing = [
        str(paths.schema_path(env))
        for env in USER_ENVIRONMENTS
        if not paths.schema_path(env).is_file()
    ]
    if missing:
        raise BuildError(f"Schema files not found: {', '.join(missing)}")
    try:
        return merge_schemas(
            {
                env: paths.schema_path(env).read_text(encoding="utf-8")
                for env in USER_ENVIRONMENTS
            }
        )
    except SchemaMergeError as exc:
        raise BuildError(str(exc)) from exc


def _environment_schema(paths: BuildPaths, environment: str):
    return build_ast_schema(
        parse(paths.schema_path(environment).read_text(encoding="utf-8"))
    )


def _check_conflicting_selections(paths: BuildPaths, merged: MergedSchema) -> None:
    """
    Fail naming each selected field that rule 4 left out of the merged schema.
    """
    conflicts_by_field: dict[str, TypeConflict] = {}
    for conflict in merged.conflicts:
        conflicts_by_field.setdefault(conflict.coordinate.split("(")[0], conflict)
    if not conflicts_by_field:
        return
    try:
        document = parse(load_graphql_files_from_path(paths.operations_dir))
    except (CodeGenException, GraphQLError) as exc:
        raise BuildError(f"Operations could not be read: {exc}") from exc

    found: list[str] = []
    type_info = TypeInfo(build_ast_schema(merged.document))

    class _Finder(Visitor):
        definition = ""

        def enter_operation_definition(self, node, *_args) -> None:
            self.definition = node.name.value if node.name else "anonymous"

        def enter_fragment_definition(self, node, *_args) -> None:
            self.definition = node.name.value

        def enter_field(self, node: FieldNode, *_args) -> None:
            parent = type_info.get_parent_type()
            if parent is None:
                return
            conflict = conflicts_by_field.get(f"{parent.name}.{node.name.value}")
            if conflict is not None:
                listed = ", ".join(f"{t} on {env}" for env, t in conflict.types)
                found.append(f"  {conflict.coordinate} in {self.definition}: {listed}")

    visit(document, TypeInfoVisitor(type_info, _Finder()))
    if found:
        raise BuildError(
            "Operations select fields whose type differs between environments:\n"
            + "\n".join(found)
        )


def _run_codegen(paths: BuildPaths) -> tuple[list[str], DefaultsReport]:
    """
    Generate the client from the merged schema.

    Returns each embedded operation, and where ``None`` defaults went.
    """
    with paths.codegen_config.open("rb") as config_file:
        config = tomllib.load(config_file)
    captured: list[str] = []
    config["tool"]["ariadne-codegen"].update(
        schema_path=str(paths.merged_schema_path),
        queries_path=str(paths.operations_dir),
        target_package_path=str(paths.package_dir.parent),
        target_package_name=paths.package_dir.name,
    )
    defaults = DefaultsReport()
    config["tool"]["gpp-client"] = {
        CAPTURE_KEY: captured,
        DEFAULTS_KEY: defaults,
    }

    if paths.package_dir.is_dir():
        shutil.rmtree(paths.package_dir)
    paths.package_dir.parent.mkdir(parents=True, exist_ok=True)
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            run_ariadne_codegen(config)
    except (CodeGenException, GraphQLError) as exc:
        raise BuildError(f"Codegen failed: {exc}") from exc
    return captured, defaults


def _check_environment_defaults(package_dir: Path, report: DefaultsReport) -> None:
    """
    Fail naming each environment-specific selection whose model lacks a None default.

    Read from the generated source, so a field the plugin matched wrongly, or a
    default a later plugin removed, cannot pass unnoticed.
    """
    fields: dict[tuple[str, str], list[ast.expr | None]] = {}
    for module in package_dir.glob("*.py"):
        for node in ast.walk(ast.parse(module.read_text(encoding="utf-8"))):
            if not isinstance(node, ast.ClassDef):
                continue
            for statement in node.body:
                if isinstance(statement, ast.AnnAssign) and isinstance(
                    statement.target, ast.Name
                ):
                    fields.setdefault((node.name, statement.target.id), []).append(
                        statement.value
                    )

    defaulted = {
        offset
        for offset, class_name, attribute in report.placed
        if fields.get((class_name, attribute))
        and all(_defaults_to_none(value) for value in fields[class_name, attribute])
    }
    missing = sorted(
        {
            description
            for offset, description in report.expected.items()
            if offset not in defaulted
        }
    )
    if missing:
        raise BuildError(
            "Environment-specific fields did not get a None default:\n"
            + "\n".join(f"  {description}" for description in missing)
        )


def _defaults_to_none(value: ast.expr | None) -> bool:
    if isinstance(value, ast.Constant):
        return value.value is None
    if isinstance(value, ast.Call):
        return any(
            keyword.arg == "default"
            and isinstance(keyword.value, ast.Constant)
            and keyword.value.value is None
            for keyword in value.keywords
        )
    return False


def _check_lookup_finds_sent_operations(
    paths: BuildPaths,
    generated: dict[str, str],
    trimmed: list[EnvironmentOperations],
) -> None:
    """
    Fail naming each query in the generated client that the lookup misses.

    The queries are read back from the generated client's source, so a change
    in how ariadne-codegen embeds them can never send an untrimmed query.
    """
    queries = _embedded_queries(paths.package_dir / "client.py")
    if len(queries) != len(generated):
        raise BuildError(
            "Reading gql(...) queries back from the generated client found "
            f"{len(queries)} of {len(generated)} generated operations."
        )
    missing: dict[str, list[str]] = {}
    for query in queries:
        for environment in trimmed:
            found = lookup_trimmed_operation(
                generated, environment.operations, environment.fragments, query
            )
            if found is None:
                missing.setdefault(_operation_name(query), []).append(
                    environment.environment
                )
    if missing:
        lines = [f"  {name} on {', '.join(envs)}" for name, envs in missing.items()]
        raise BuildError(
            "The generated client sends operations the trimmed lookup cannot find:\n"
            + "\n".join(lines)
        )


def _embedded_queries(client_path: Path) -> list[str]:
    return _embedded_queries_in(ast.parse(client_path.read_text(encoding="utf-8")))


def _embedded_queries_in(tree: ast.AST) -> list[str]:
    return [
        node.args[0].value
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "gql"
        and node.args
        and isinstance(node.args[0], ast.Constant)
    ]


def _operation_name(query: str) -> str:
    for definition in parse(query).definitions:
        if isinstance(definition, OperationDefinitionNode) and definition.name:
            return definition.name.value
    return "anonymous"


def _trim_summary(trimmed: list[EnvironmentOperations]) -> str:
    sections = []
    for environment in trimmed:
        lines = []
        if environment.unavailable:
            lines.append(f"- Unavailable: {_names(environment.unavailable)}")
        lines += [
            f"- `{part}` removed from {_names(definitions)}"
            for part, definitions in environment.removed.items()
        ]
        if lines:
            sections.append(f"**{environment.environment}**\n" + "\n".join(lines))
        else:
            sections.append(f"**{environment.environment}**: nothing trimmed.")
    return "### Trim summary\n\n" + "\n\n".join(sections) + "\n"


def _names(names: tuple[str, ...]) -> str:
    return ", ".join(f"`{name}`" for name in names)


def _write_trimmed(
    package_dir: Path,
    generated: dict[str, str],
    trimmed: list[EnvironmentOperations],
) -> None:
    trimmed_dir = package_dir / "trimmed"
    trimmed_dir.mkdir()
    (trimmed_dir / "__init__.py").write_text(
        '"""Operations trimmed per environment. Generated; do not edit."""\n\n'
        f"GENERATED = {_dict_lines(generated.items())}\n",
        encoding="utf-8",
    )
    for environment in trimmed:
        operations = sorted(
            environment.operations.items(), key=lambda item: (item[1][0], item[0])
        )
        (trimmed_dir / f"{environment.environment}.py").write_text(
            f'"""Operations as {environment.environment} receives them. '
            'Generated; do not edit."""\n\n'
            f"FRAGMENTS = {_dict_lines(environment.fragments.items())}\n\n"
            f"OPERATIONS = {_dict_lines(operations)}\n",
            encoding="utf-8",
        )


def _view_name(environment: str) -> str:
    return f"{environment.capitalize()}GraphQLClient"


_SHARED_VIEW = "SharedGraphQLClient"
_ALL_VIEWS = "EveryEnvironmentGraphQLClient"


def _environment_clients() -> dict[tuple[str, ...], tuple[str, str]]:
    """
    Return each typed view of the generated client, keyed by the environments
    that have the methods it adds: its name and its base.
    """
    views = {USER_ENVIRONMENTS: (_SHARED_VIEW, "AsyncBaseClient")}
    views.update({(env,): (_view_name(env), _SHARED_VIEW) for env in USER_ENVIRONMENTS})
    return views


def _method_environments(
    package_dir: Path, trimmed: list[EnvironmentOperations]
) -> dict[str, tuple[str, ...]]:
    """
    Return each public generated client method with the environments that have it.

    A method's environments come from the trimmed operations: an environment
    where any operation the method sends is unavailable does not have it.
    """
    unavailable = {
        environment.environment: {
            digest
            for digest, (_, text, _) in environment.operations.items()
            if text is None
        }
        for environment in trimmed
    }
    tree = ast.parse((package_dir / "client.py").read_text(encoding="utf-8"))
    client = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == "GraphQLClient"
    )
    found: dict[str, tuple[str, ...]] = {}
    for method in client.body:
        if not isinstance(
            method, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) or method.name.startswith("_"):
            continue
        digests = {operation_digest(query) for query in _embedded_queries_in(method)}
        found[method.name] = tuple(
            environment
            for environment in USER_ENVIRONMENTS
            if not digests & unavailable[environment]
        )
    return found


def _write_environment_clients(
    package_dir: Path, method_environments: dict[str, tuple[str, ...]]
) -> None:
    """
    Write a view of the generated client per environment, for type checkers.

    A view lists only the client methods its environment has, so a type checker
    flags a call to an operation the environment lacks. Each method is the
    generated one, so the editor shows its own signature and docstring.
    """
    views = _environment_clients()
    methods: dict[tuple[str, ...], list[str]] = {key: [] for key in views}
    for name, environments in method_environments.items():
        available_on = tuple(
            environment
            for environment in USER_ENVIRONMENTS
            if environment in environments
        )
        if available_on:
            methods[available_on].append(name)

    classes = []
    for environments, (name, base) in views.items():
        lines = [
            f"class {name}({base}):",
            '    """',
            f"    The generated client methods on {' and '.join(environments)}.",
            '    """',
        ]
        if methods[environments]:
            lines.append("")
        lines += [f"    {m} = GraphQLClient.{m}" for m in methods[environments]]
        classes.append("\n".join(lines) + "\n")
    every_view = ", ".join(_view_name(env) for env in USER_ENVIRONMENTS)
    classes.append(
        f"class {_ALL_VIEWS}({every_view}):\n"
        '    """\n'
        "    Every environment's view, so the full client is typed as each one.\n"
        '    """\n'
    )
    (package_dir / "environment_clients.py").write_text(
        '"""Typed views of the generated client per environment. '
        'Generated; do not edit."""\n\n'
        "from .async_base_client import AsyncBaseClient\n"
        "from .client import GraphQLClient\n\n\n" + "\n\n".join(classes),
        encoding="utf-8",
    )


BUNDLED_SCHEMAS_DIR = "schemas"
"""Folder in the generated package holding each environment's schema."""


def _write_bundled_schemas(paths: BuildPaths) -> None:
    """
    Copy each environment's schema into the package, without descriptions.

    The client checks every call against them before sending, generated
    operations as each environment's trimmed copy; descriptions play no part in
    that.
    """
    schemas_dir = paths.package_dir / BUNDLED_SCHEMAS_DIR
    schemas_dir.mkdir()
    for environment in USER_ENVIRONMENTS:
        document = parse(
            paths.schema_path(environment).read_text(encoding="utf-8"),
            no_location=True,
        )
        (schemas_dir / f"{environment}.graphql").write_text(
            print_ast(visit(document, _DropDescriptions())) + "\n", encoding="utf-8"
        )


class _DropDescriptions(Visitor):
    def enter(self, node, *_args):
        if getattr(node, "description", None) is None:
            return None
        without = copy.copy(node)
        without.description = None
        return without


def _availability_notes(
    methods: dict[str, tuple[str, ...]],
    tables: AvailabilityTables,
    trimmed: list[EnvironmentOperations],
) -> AvailabilityNotes:
    return AvailabilityNotes(
        methods=methods,
        inputs=tables.available,
        required=tables.required,
        missing_fields={
            environment.environment: tuple(
                part for part in environment.removed if _FIELD.fullmatch(part)
            )
            for environment in trimmed
        },
        leaving=tuple(
            sorted(
                {
                    field
                    for fields in tables.leaving.values()
                    for field, environments in fields.items()
                    if "production" in environments
                }
            )
        ),
    )


_FIELD = re.compile(r"\w+\.\w+")
"""A removed part that is a field (``Type.field``), not an argument or fragment."""


def _dict_lines(items) -> str:
    """
    Return a dict literal with one entry per line, so schema PRs diff per entry.
    """
    lines = "".join(f"    {key!r}: {value!r},\n" for key, value in items)
    return "{\n" + lines + "}"


@app.command()
def main() -> None:
    """
    Build the merged schema, the generated client and the trimmed operations.
    """
    paths = BuildPaths.for_repo(Path.cwd())
    try:
        with output.status("Building..."):
            result = build(paths)
    except BuildError as exc:
        output.fail(escape(str(exc)))
        raise typer.Exit(code=1) from exc

    for conflict in result.conflicts:
        types = ", ".join(f"{t} on {env}" for env, t in conflict.types)
        output.warning(f"Left out {conflict.coordinate}: type differs ({types}).")
    output.success(
        f"Wrote {result.merged_schema_path}, {paths.package_dir} and {paths.llms_txt}"
    )
    # Plain text, so it pastes into a PR body unchanged.
    typer.echo("\n" + result.trim_summary)


if __name__ == "__main__":
    app()
