# Generated by ariadne-codegen
# Source: queries/

from typing import Any, Dict, List, Optional, Tuple, Union

from graphql import (
    DocumentNode,
    NamedTypeNode,
    NameNode,
    OperationDefinitionNode,
    OperationType,
    SelectionNode,
    SelectionSetNode,
    VariableDefinitionNode,
    VariableNode,
    print_ast,
)

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .base_operation import GraphQLField
from .create_program_note import CreateProgramNote
from .get_all_program_notes import GetAllProgramNotes
from .get_program_note import GetProgramNote
from .input_types import ProgramNotePropertiesInput, WhereProgramNote
from .update_program_notes import UpdateProgramNotes


def gql(q: str) -> str:
    return q


class _GPPClient(AsyncBaseClient):
    async def get_all_program_notes(
        self,
        include_deleted: bool,
        where: Union[Optional[WhereProgramNote], UnsetType] = UNSET,
        offset: Union[Optional[str], UnsetType] = UNSET,
        limit: Union[Optional[Any], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetAllProgramNotes:
        query = gql(
            """
            query GetAllProgramNotes($includeDeleted: Boolean!, $where: WhereProgramNote, $offset: ProgramNoteId, $limit: NonNegInt) {
              programNotes(
                includeDeleted: $includeDeleted
                WHERE: $where
                OFFSET: $offset
                LIMIT: $limit
              ) {
                hasMore
                matches {
                  ...ProgramNoteFields
                }
              }
            }

            fragment ProgramNoteFields on ProgramNote {
              id
              title
              text
              isPrivate
              existence
              program {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "includeDeleted": include_deleted,
            "where": where,
            "offset": offset,
            "limit": limit,
        }
        response = await self.execute(
            query=query,
            operation_name="GetAllProgramNotes",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetAllProgramNotes.model_validate(data)

    async def create_program_note(
        self,
        input: ProgramNotePropertiesInput,
        program_id: Union[Optional[str], UnsetType] = UNSET,
        proposal_reference: Union[Optional[Any], UnsetType] = UNSET,
        program_reference: Union[Optional[Any], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CreateProgramNote:
        query = gql(
            """
            mutation CreateProgramNote($programId: ProgramId, $proposalReference: ProposalReferenceLabel, $programReference: ProgramReferenceLabel, $input: ProgramNotePropertiesInput!) {
              createProgramNote(
                input: {programId: $programId, proposalReference: $proposalReference, programReference: $programReference, SET: $input}
              ) {
                programNote {
                  ...ProgramNoteFields
                }
              }
            }

            fragment ProgramNoteFields on ProgramNote {
              id
              title
              text
              isPrivate
              existence
              program {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "programId": program_id,
            "proposalReference": proposal_reference,
            "programReference": program_reference,
            "input": input,
        }
        response = await self.execute(
            query=query,
            operation_name="CreateProgramNote",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CreateProgramNote.model_validate(data)

    async def update_program_notes(
        self,
        set: ProgramNotePropertiesInput,
        where: Union[Optional[WhereProgramNote], UnsetType] = UNSET,
        limit: Union[Optional[Any], UnsetType] = UNSET,
        include_deleted: Union[Optional[bool], UnsetType] = UNSET,
        **kwargs: Any
    ) -> UpdateProgramNotes:
        query = gql(
            """
            mutation UpdateProgramNotes($set: ProgramNotePropertiesInput!, $where: WhereProgramNote, $limit: NonNegInt, $includeDeleted: Boolean = false) {
              updateProgramNotes(
                input: {SET: $set, WHERE: $where, LIMIT: $limit, includeDeleted: $includeDeleted}
              ) {
                hasMore
                programNotes {
                  ...ProgramNoteFields
                }
              }
            }

            fragment ProgramNoteFields on ProgramNote {
              id
              title
              text
              isPrivate
              existence
              program {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "set": set,
            "where": where,
            "limit": limit,
            "includeDeleted": include_deleted,
        }
        response = await self.execute(
            query=query,
            operation_name="UpdateProgramNotes",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateProgramNotes.model_validate(data)

    async def get_program_note(self, id: str, **kwargs: Any) -> GetProgramNote:
        query = gql(
            """
            query GetProgramNote($id: ProgramNoteId!) {
              programNote(programNoteId: $id) {
                ...ProgramNoteFields
              }
            }

            fragment ProgramNoteFields on ProgramNote {
              id
              title
              text
              isPrivate
              existence
              program {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetProgramNote", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetProgramNote.model_validate(data)

    async def execute_custom_operation(
        self, *fields: GraphQLField, operation_type: OperationType, operation_name: str
    ) -> Dict[str, Any]:
        selections = self._build_selection_set(fields)
        combined_variables = self._combine_variables(fields)
        variable_definitions = self._build_variable_definitions(
            combined_variables["types"]
        )
        operation_ast = self._build_operation_ast(
            selections, operation_type, operation_name, variable_definitions
        )
        response = await self.execute(
            print_ast(operation_ast),
            variables=combined_variables["values"],
            operation_name=operation_name,
        )
        return self.get_data(response)

    def _combine_variables(
        self, fields: Tuple[GraphQLField, ...]
    ) -> Dict[str, Dict[str, Any]]:
        variables_types_combined = {}
        processed_variables_combined = {}
        for field in fields:
            formatted_variables = field.get_formatted_variables()
            variables_types_combined.update(
                {k: v["type"] for k, v in formatted_variables.items()}
            )
            processed_variables_combined.update(
                {k: v["value"] for k, v in formatted_variables.items()}
            )
        return {
            "types": variables_types_combined,
            "values": processed_variables_combined,
        }

    def _build_variable_definitions(
        self, variables_types_combined: Dict[str, str]
    ) -> List[VariableDefinitionNode]:
        return [
            VariableDefinitionNode(
                variable=VariableNode(name=NameNode(value=var_name)),
                type=NamedTypeNode(name=NameNode(value=var_value)),
            )
            for var_name, var_value in variables_types_combined.items()
        ]

    def _build_operation_ast(
        self,
        selections: List[SelectionNode],
        operation_type: OperationType,
        operation_name: str,
        variable_definitions: List[VariableDefinitionNode],
    ) -> DocumentNode:
        return DocumentNode(
            definitions=[
                OperationDefinitionNode(
                    operation=operation_type,
                    name=NameNode(value=operation_name),
                    variable_definitions=variable_definitions,
                    selection_set=SelectionSetNode(selections=selections),
                )
            ]
        )

    def _build_selection_set(
        self, fields: Tuple[GraphQLField, ...]
    ) -> List[SelectionNode]:
        return [field.to_ast(idx) for idx, field in enumerate(fields)]

    async def query(self, *fields: GraphQLField, operation_name: str) -> Dict[str, Any]:
        return await self.execute_custom_operation(
            *fields, operation_type=OperationType.QUERY, operation_name=operation_name
        )

    async def mutation(
        self, *fields: GraphQLField, operation_name: str
    ) -> Dict[str, Any]:
        return await self.execute_custom_operation(
            *fields,
            operation_type=OperationType.MUTATION,
            operation_name=operation_name
        )
