# Generated by ariadne-codegen
# Source: queries/

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProgramNoteFields


class CreateProgramNote(BaseModel):
    create_program_note: "CreateProgramNoteCreateProgramNote" = Field(
        alias="createProgramNote"
    )


class CreateProgramNoteCreateProgramNote(BaseModel):
    program_note: "CreateProgramNoteCreateProgramNoteProgramNote" = Field(
        alias="programNote"
    )


class CreateProgramNoteCreateProgramNoteProgramNote(ProgramNoteFields):
    pass


CreateProgramNote.model_rebuild()
CreateProgramNoteCreateProgramNote.model_rebuild()
