# Generated by ariadne-codegen
# Source: queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import Existence


class ProgramNoteFields(BaseModel):
    id: str
    title: str
    text: Optional[str]
    is_private: bool = Field(alias="isPrivate")
    existence: Existence
    program: "ProgramNoteFieldsProgram"


class ProgramNoteFieldsProgram(BaseModel):
    id: str


ProgramNoteFields.model_rebuild()
