# Generated by ariadne-codegen
# Source: src/queries

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ProgramType, ProposalStatus, ScienceBand


class GetGOATSPrograms(BaseModel):
    programs: "GetGOATSProgramsPrograms"


class GetGOATSProgramsPrograms(BaseModel):
    matches: List["GetGOATSProgramsProgramsMatches"]
    has_more: bool = Field(alias="hasMore")


class GetGOATSProgramsProgramsMatches(BaseModel):
    id: Any
    name: Optional[Any]
    description: Optional[Any]
    reference: Optional["GetGOATSProgramsProgramsMatchesReference"]
    proposal_status: ProposalStatus = Field(alias="proposalStatus")
    type: ProgramType
    time_charge: List["GetGOATSProgramsProgramsMatchesTimeCharge"] = Field(
        alias="timeCharge"
    )
    allocations: List["GetGOATSProgramsProgramsMatchesAllocations"]


class GetGOATSProgramsProgramsMatchesReference(BaseModel):
    typename__: Literal[
        "CalibrationProgramReference",
        "CommissioningProgramReference",
        "EngineeringProgramReference",
        "ExampleProgramReference",
        "LibraryProgramReference",
        "MonitoringProgramReference",
        "ProgramReference",
        "ScienceProgramReference",
        "SystemProgramReference",
    ] = Field(alias="__typename")
    label: Any


class GetGOATSProgramsProgramsMatchesTimeCharge(BaseModel):
    band: Optional[ScienceBand]
    time: "GetGOATSProgramsProgramsMatchesTimeChargeTime"


class GetGOATSProgramsProgramsMatchesTimeChargeTime(BaseModel):
    program: "GetGOATSProgramsProgramsMatchesTimeChargeTimeProgram"


class GetGOATSProgramsProgramsMatchesTimeChargeTimeProgram(BaseModel):
    hours: Any


class GetGOATSProgramsProgramsMatchesAllocations(BaseModel):
    science_band: ScienceBand = Field(alias="scienceBand")
    duration: "GetGOATSProgramsProgramsMatchesAllocationsDuration"


class GetGOATSProgramsProgramsMatchesAllocationsDuration(BaseModel):
    hours: Any


GetGOATSPrograms.model_rebuild()
GetGOATSProgramsPrograms.model_rebuild()
GetGOATSProgramsProgramsMatches.model_rebuild()
GetGOATSProgramsProgramsMatchesTimeCharge.model_rebuild()
GetGOATSProgramsProgramsMatchesTimeChargeTime.model_rebuild()
GetGOATSProgramsProgramsMatchesAllocations.model_rebuild()
