# Generated by ariadne-codegen
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProgramNoteFields


class GetAllProgramNotes(BaseModel):
    program_notes: "GetAllProgramNotesProgramNotes" = Field(alias="programNotes")


class GetAllProgramNotesProgramNotes(BaseModel):
    has_more: bool = Field(alias="hasMore")
    matches: List["GetAllProgramNotesProgramNotesMatches"]


class GetAllProgramNotesProgramNotesMatches(ProgramNoteFields):
    pass


GetAllProgramNotes.model_rebuild()
GetAllProgramNotesProgramNotes.model_rebuild()
