# Generated by ariadne-codegen
# Source: queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProgramNoteFields


class GetProgramNote(BaseModel):
    program_note: Optional["GetProgramNoteProgramNote"] = Field(alias="programNote")


class GetProgramNoteProgramNote(ProgramNoteFields):
    pass


GetProgramNote.model_rebuild()
