# Generated by ariadne-codegen
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProgramNoteFields


class UpdateProgramNotes(BaseModel):
    update_program_notes: "UpdateProgramNotesUpdateProgramNotes" = Field(
        alias="updateProgramNotes"
    )


class UpdateProgramNotesUpdateProgramNotes(BaseModel):
    has_more: bool = Field(alias="hasMore")
    program_notes: List["UpdateProgramNotesUpdateProgramNotesProgramNotes"] = Field(
        alias="programNotes"
    )


class UpdateProgramNotesUpdateProgramNotesProgramNotes(ProgramNoteFields):
    pass


UpdateProgramNotes.model_rebuild()
UpdateProgramNotesUpdateProgramNotes.model_rebuild()
