[tool.ariadne-codegen]
schema_path = "graphql/schemas/development.graphql"
queries_path = "build/graphql/development"
target_package_path = "src/gpp_client"
target_package_name = "generated"
client_name = "GraphQLClient"
client_file_name = "client"
plugins = ["custom_plugins.AliasStrWrapperPlugin"]
enable_custom_operations = true
convert_to_snake_case = true
include_comments = "none"
